sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: xxxxx
    port: 3306
    database: sky_take_out
    username: root
    password: 1xxxxxxx
  alioss:
    endpoint: xxxxxx
    access-key-id: xxxx
    access-key-secret: xxxxxx
    bucket-name: xxxxx
