sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 106.14.202.122
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tCbBTivvTzxnyzqwasr
    access-key-secret: 2E2EwawbeeL1qInoL8lLqPHmnF6wLN
    bucket-name: web-tlias-ncy
#  redis:
#    host: 106.14.202.122
#    port: 6379
#    password: 123456
#    database: 10